// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eaeqyctjljbtcatlohky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhZXF5Y3RqbGpidGNhdGxvaGt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODE1OTgsImV4cCI6MjA2MTM1NzU5OH0.FrxmM9nqPNUjo3ZTMUdUWPirm0q1WFssoierxq9zb7A";

// Singleton across HMR reloads / accidental re-imports.
// Without this, Vite HMR can produce multiple GoTrueClient instances on the
// same storage key, causing duplicate auth listeners and refresh races.
const SUPABASE_SINGLETON_KEY = '__fanrealms_supabase_client__';

type GlobalWithSupabase = typeof globalThis & {
  [SUPABASE_SINGLETON_KEY]?: SupabaseClient<Database>;
};

const globalRef = globalThis as GlobalWithSupabase;

export const supabase: SupabaseClient<Database> =
  globalRef[SUPABASE_SINGLETON_KEY] ??
  (globalRef[SUPABASE_SINGLETON_KEY] = createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
        flowType: 'pkce',
        detectSessionInUrl: true,
        storageKey: 'fanrealms-auth',
      },
    }
  ));
